Numpy는 Python의 수치 계산을 위한 라이브러리입니다. Numpy를 이용하면 배열(array)을 사용해 빠르고 효율적인 수치 연산을 수행할 수 있습니다.

In [1]:
import numpy as np

## 배열 생성:
* Numpy에서 가장 중요한 객체는 다차원 배열(ndarray)입니다. 다음은 배열을 생성하는 몇 가지 방법입니다.

### 리스트를 사용한 배열 생성:

In [3]:
a = np.array([1, 2, 3])   # 1차원 배열
b = np.array([[1, 2, 3], [4, 5, 6]])   # 2차원 배열

print(a)

[1 2 3]


In [4]:
print(b)

[[1 2 3]
 [4 5 6]]


### 초기값과 크기를 지정한 배열 생성:

In [5]:
zeros = np.zeros((3, 3))   # 모든 요소가 0인 3x3 배열 생성
ones = np.ones((2, 2))     # 모든 요소가 1인 2x2 배열 생성

print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
print(ones)

[[1. 1.]
 [1. 1.]]


### 배열 속성 및 인덱싱:

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print(a.shape)  # 배열의 크기: (2, 3)
print(a.ndim)   # 배열의 차원: 2
print(a.size)   # 배열의 요소 개수: 6

(2, 3)
2
6
2
[1 4]


In [8]:
# 인덱싱 및 슬라이싱
print(a[0, 1])  # 1행 2열 요소: 2
print(a[:, 0])  # 첫 번째 열: array([1, 4])

2
[1 4]


## 배열 연산:
* Numpy는 기본적인 사칙 연산, 선형 대수 연산 등 다양한 수학 연산을 지원합니다.

### 기본 사칙 연산:

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # array([5, 7, 9])
print(a * b)  # array([ 4, 10, 18])

[5 7 9]
[ 4 10 18]


### 행렬 곱:

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))  # array([[19, 22], [43, 50]])

[[19 22]
 [43 50]]


### 브로드캐스팅:
* Numpy는 브로드캐스팅 기능을 통해 서로 다른 크기의 배열 간 연산을 쉽게 수행할 수 있습니다. 브로드캐스팅은 작은 배열이 큰 배열의 크기에 맞춰 자동으로 확장되어 연산이 가능하게 하는 기능입니다.

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 0, 1])

# 브로드캐스팅을 사용한 연산
c = a + b  # b가 a의 크기에 맞춰 확장되어 연산됩니다.
print(c)
# 출력 결과:
# array([[ 2,  2,  4],
#        [ 5,  5,  7],
#        [ 8,  8, 10]])

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


### 유용한 Numpy 함수들:
* np.arange(start, stop, step) : start부터 stop까지 step 간격의 숫자를 생성한 후 배열로 반환합니다.

In [12]:
# np.arange 예시
a = np.arange(0, 10, 2)
print(a)  # 출력 결과: array([0, 2, 4, 6, 8])

[0 2 4 6 8]


* np.linspace(start, stop, num) : start부터 stop까지 균일한 간격으로 num개의 숫자를 생성한 후 배열로 반환합니다.

In [13]:
# np.linspace 예시
b = np.linspace(0, 1, 5)
print(b)  # 출력 결과: array([0.  , 0.25, 0.5 , 0.75, 1.  ])

[0.   0.25 0.5  0.75 1.  ]


* np.reshape(a, new_shape) : 주어진 배열 a를 new_shape로 변경한 새로운 배열을 반환합니다.

In [14]:
# np.reshape 예시
c = np.array([1, 2, 3, 4, 5, 6])
d = np.reshape(c, (2, 3))
print(d)
# 출력 결과:
# array([[1, 2, 3],
#        [4, 5, 6]])

[[1 2 3]
 [4 5 6]]


* np.sum(a, axis) : 주어진 배열 a의 모든 요소의 합계를 계산하며, axis를 지정하면 해당 축을 따라 합계를 계산합니다.

In [15]:
# np.sum 예시
e = np.array([[1, 2, 3], [4, 5, 6]])
f = np.sum(e)
print(f)  # 출력 결과: 21

21


* np.mean(a, axis) : 주어진 배열 a의 모든 요소의 평균을 계산하며, axis를 지정하면 해당 축을 따라 평균을 계산합니다.

In [16]:
# np.mean 예시
g = np.array([[1, 2, 3], [4, 5, 6]])
h = np.mean(g)
print(h)  # 출력 결과: 3.5

3.5


* np.max(a, axis) : 주어진 배열 a의 최대값을 찾습니다. axis를 지정하면 해당 축을 따라 최대값을 찾습니다.

In [17]:
# np.max 예시
i = np.array([[1, 2, 3], [4, 5, 6]])
j = np.max(i)
print(j)  # 출력 결과: 6

6


* np.min(a, axis) : 주어진 배열 a의 최소값을 찾습니다. axis를 지정하면 해당 축을 따라 최소값을 찾습니다.

In [18]:
# np.min 예시
k = np.array([[1, 2, 3], [4, 5, 6]])
l = np.min(k)
print(l)  # 출력 결과: 1

1
